name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/arm64/v8
          - linux/amd64
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Pull
        run: git pull origin master
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            -o Acquire::Retries=5 \
            make build-essential libssl-dev pkg-config libjansson-dev \
            libwebsockets-dev libcurl4-openssl-dev libmicrohttpd-dev \
            git clone --depth=1 https://github.com/briandowns/libmaple.git && \
            cd libmaple && make && sudo make install && \
            cd .. && rm -rf libmaple && \
            git clone --depth=1 https://github.com/briandowns/liblogger.git && \
            cd liblogger && make && sudo make install && \
            cd .. && rm -rf liblogger && \
            sudo ldconfig && \
            sudo apt-get autoremove -y && \
            sudo apt-get clean -y && \
            sudo rm -rf /var/lib/apt/lists/* && \
            sudo rm -rf /tmp/* /var/tmp/* && \
            echo "Dependencies installed successfully"
      - name: Compile Shared Object
        run: make
      # - name: Run tests
      #   run: make tests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Example
        run: make example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build All Examples
        run: make examples_all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
