name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/arm64/v8
          - linux/amd64
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Pull
        run: git pull origin master
      - name: Install Dependencies
        run: |
          if [ "${RUNNER_OS}" == "Linux" ]; then
            sudo apt install -y make build-essential libssl-dev pkg-config libjansson-dev libwebsockets-dev libcurl4-openssl-dev libmicrohttpd-dev
          elif [ "${RUNNER_OS}" == "macOS" ]; then
            brew update
            brew uninstall curl
            brew install curl-openssl
          fi
      - name: Compile Shared Object
        run: make
      # - name: Run tests
      #   run: make tests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Example
        run: make example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build All Examples
        run: make examples_all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
